baseURL = "http://localhost:1313/syntonie/"
languageCode = "fr-BE"
title = "Syntonie"

disableKinds = ["taxonomy", "term"]

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "data"
  target = "static/data"

[params]
  description = "ASBL · Infrastructure de gouvernance pour l'écosystème Trinity · Ixelles, Bruxelles"
